AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy a Fedora development EC2 instance with Zsh, Antigen, autocompletions, autosuggestions, and Starship prompt'

Parameters:
  KeyPairName:
    Description: 'The EC2 key pair name for SSH access'
    Type: 'AWS::EC2::KeyPair::KeyName'

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  FedoraAMIIdLookup:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
      Type: 'String'

  FedoraInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref FedoraAMIIdLookup
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf -y update
          dnf -y groupinstall "Development Tools"
          dnf -y install git wget curl zsh 
          useradd -m -s /bin/zsh rune
          echo "rune ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          # Install Antigen
          sudo -u rune sh -c "curl -L git.io/antigen > /home/rune/antigen.zsh"

          # Create .zshrc for rune
          sudo -u rune tee /home/rune/.zshrc > /dev/null << EOT
          source /home/rune/antigen.zsh
          
          antigen bundle git
          antigen bundle zsh-users/zsh-autosuggestions
          antigen bundle zsh-users/zsh-syntax-highlighting
          antigen bundle Aloxaf/fzf-tab
          antigen apply

          eval "\$(starship init zsh)"
          EOT

          # Install Starship prompt
          curl -fsSL https://starship.rs/install.sh | sudo -u rune bash -s -- -y

Outputs:
  InstanceId:
    Description: The instance ID
    Value: !Ref FedoraInstance
  PublicIP:
    Description: The public IP address of the instance
    Value: !GetAtt FedoraInstance.PublicIp
  PublicDNS:
    Description: The public DNS name of the instance
    Value: !GetAtt FedoraInstance.PublicDnsName
