---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an EC2 instance running Fedora with EBS volume attached'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: 'Instance type for the EC2 instance'
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: 'Name of an existing EC2 key pair'

Resources:
  FedoraEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0c94855ba95c71c99' # Fedora 33 (free tier eligible)
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd

  DataVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: !GetAtt FedoraEC2Instance.AvailabilityZone
      Size: '10'
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: FedoraDataVolume

  DataVolumeAttachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref FedoraEC2Instance
      VolumeId: !Ref DataVolume
      Device: /dev/sdf

Outputs:
  EC2InstanceIP:
    Description: 'Public IP address of the EC2 instance'
    Value: !GetAtt FedoraEC2Instance.PublicIp
  DataVolumeID:
    Description: 'ID of the EBS volume attached to the EC2 instance'
    Value: !Ref DataVolume

