# CloudFormation YAML template for an (opinionated) Gentoo EC2 instance

AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: String
    Description: Name of an existing EC2 key pair to enable SSH access to the instances.
  InstanceType:
    Type: String
    Description: Instance type to launch, e.g. t2.micro
    Default: t2.micro
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC to deploy the instance in
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Select the Subnet to deploy the instance in

Resources:
  LatestAmiLookup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-examples/latest-amazon-linux-2-ami.yaml
      Parameters:
        Region: !Ref AWS::Region
        Arch: x86_64
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !GetAtt LatestAmiLookup.Outputs.ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - GroupSet:
            - !Ref SecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: MyInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y git
          git clone https://github.com/gentoo/gentoo.git /usr/portage
          emerge-webrsync -v
          emerge --ask --verbose --update --deep --newuse @world
          echo 'exec /bin/bash' >> /etc/init.d/rc.local
          rc-update add default
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0